//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPlace
    {
        public OrderPlace()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string PlaceName { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
